language: python
matrix:
    include:
        - python: 3.6

install:
  # install PyTorch
  - pip install torch --upgrade --upgrade-strategy only-if-needed
  - pip install -e .

# command to run tests
script:
  - nosetests